include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    depend_on_referenced_packages: false
    sized_box_for_whitespace: false
    use_key_in_widget_constructors: false
    sort_child_properties_last: false
    unnecessary_overrides: false
    prefer_typing_uninitialized_variables: false
    curly_braces_in_flow_control_structures: false
    avoid_print: false
    prefer_single_quotes: false
    avoid_unnecessary_containers: false
    unnecessary_new: false
    constant_identifier_names: false
    use_build_context_synchronously: false
    unrelated_type_equality_checks: false
