name: ai_chatbot
description: AI Chat.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  audioplayers: ^3.0.1
  cupertino_icons: ^1.0.5
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  siri_wave: ^0.3.0
  speech_to_text: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
